version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: keycloak_ctn
    tty: true
    stdin_open: true
    ports:
      - "9090:8080"
    volumes:
      - ./data/keycloak:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev