/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.issuemanager.presentation.api;

import com.example.issuemanager.presentation.model.Error;
import com.example.issuemanager.presentation.model.IssueTicket;
import com.example.issuemanager.presentation.model.IssueTicketAssignRequest;
import com.example.issuemanager.presentation.model.IssueTicketStatusUpdateRequest;
import java.util.UUID;
import com.example.issuemanager.presentation.model.ValidationError;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-05-12T03:11:22.970089+09:00[Asia/Tokyo]", comments = "Generator version: 7.5.0")
@Validated
@Tag(name = "issues", description = "manage issue tickets")
public interface IssuesApi {

    /**
     * GET /projects/{project_id}/issues-tickets : retrieve all
     * retrieve all
     *
     * @param projectId  (required)
     * @return succeeded (status code 200)
     *         or Unauthorized (status code 401)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "projectsProjectIdIssuesTicketsGet",
        summary = "retrieve all",
        description = "retrieve all",
        tags = { "issues" },
        responses = {
            @ApiResponse(responseCode = "200", description = "succeeded", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = IssueTicket.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/projects/{project_id}/issues-tickets",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<IssueTicket>> projectsProjectIdIssuesTicketsGet(
        @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") UUID projectId
    );


    /**
     * PATCH /projects/{project_id}/issues-tickets/{issue_ticket_id}/assign : assign
     * assign issue ticket to member
     *
     * @param projectId  (required)
     * @param issueTicketId  (required)
     * @param issueTicketAssignRequest  (optional)
     * @return succeeded (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Unprocessable Entity (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "projectsProjectIdIssuesTicketsIssueTicketIdAssignPatch",
        summary = "assign",
        description = "assign issue ticket to member",
        tags = { "issues" },
        responses = {
            @ApiResponse(responseCode = "200", description = "succeeded"),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ValidationError.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Unprocessable Entity", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/projects/{project_id}/issues-tickets/{issue_ticket_id}/assign",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> projectsProjectIdIssuesTicketsIssueTicketIdAssignPatch(
        @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") UUID projectId,
        @Parameter(name = "issue_ticket_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("issue_ticket_id") UUID issueTicketId,
        @Parameter(name = "IssueTicketAssignRequest", description = "") @Valid @RequestBody(required = false) Optional<IssueTicketAssignRequest> issueTicketAssignRequest
    );


    /**
     * DELETE /projects/{project_id}/issues-tickets/{issue_ticket_id} : delete
     * delete
     *
     * @param projectId  (required)
     * @param issueTicketId  (required)
     * @return succeeded (status code 200)
     *         or Unauthorized (status code 401)
     *         or Unprocessable Entity (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "projectsProjectIdIssuesTicketsIssueTicketIdDelete",
        summary = "delete",
        description = "delete",
        tags = { "issues" },
        responses = {
            @ApiResponse(responseCode = "200", description = "succeeded"),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Unprocessable Entity", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/projects/{project_id}/issues-tickets/{issue_ticket_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> projectsProjectIdIssuesTicketsIssueTicketIdDelete(
        @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") UUID projectId,
        @Parameter(name = "issue_ticket_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("issue_ticket_id") UUID issueTicketId
    );


    /**
     * GET /projects/{project_id}/issues-tickets/{issue_ticket_id} : retrieve
     * retrieve
     *
     * @param projectId  (required)
     * @param issueTicketId  (required)
     * @return succeeded (status code 200)
     *         or Unauthorized (status code 401)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "projectsProjectIdIssuesTicketsIssueTicketIdGet",
        summary = "retrieve",
        description = "retrieve",
        tags = { "issues" },
        responses = {
            @ApiResponse(responseCode = "200", description = "succeeded", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = IssueTicket.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/projects/{project_id}/issues-tickets/{issue_ticket_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<IssueTicket> projectsProjectIdIssuesTicketsIssueTicketIdGet(
        @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") UUID projectId,
        @Parameter(name = "issue_ticket_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("issue_ticket_id") UUID issueTicketId
    );


    /**
     * PUT /projects/{project_id}/issues-tickets/{issue_ticket_id} : update
     * update
     *
     * @param projectId  (required)
     * @param issueTicketId  (required)
     * @param issueTicket  (optional)
     * @return succeeded (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Unprocessable Entity (status code 422)
     */
    @Operation(
        operationId = "projectsProjectIdIssuesTicketsIssueTicketIdPut",
        summary = "update",
        description = "update",
        tags = { "issues" },
        responses = {
            @ApiResponse(responseCode = "200", description = "succeeded"),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ValidationError.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unprocessable Entity", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/projects/{project_id}/issues-tickets/{issue_ticket_id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> projectsProjectIdIssuesTicketsIssueTicketIdPut(
        @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") UUID projectId,
        @Parameter(name = "issue_ticket_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("issue_ticket_id") UUID issueTicketId,
        @Parameter(name = "IssueTicket", description = "") @Valid @RequestBody(required = false) Optional<IssueTicket> issueTicket
    );


    /**
     * PATCH /projects/{project_id}/issues-tickets/{issue_ticket_id}/staus : update status
     * update status
     *
     * @param projectId  (required)
     * @param issueTicketId  (required)
     * @param issueTicketStatusUpdateRequest  (optional)
     * @return succeeded (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Unprocessable Entity (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "projectsProjectIdIssuesTicketsIssueTicketIdStausPatch",
        summary = "update status",
        description = "update status",
        tags = { "issues" },
        responses = {
            @ApiResponse(responseCode = "200", description = "succeeded"),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ValidationError.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Unprocessable Entity", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/projects/{project_id}/issues-tickets/{issue_ticket_id}/staus",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> projectsProjectIdIssuesTicketsIssueTicketIdStausPatch(
        @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") UUID projectId,
        @Parameter(name = "issue_ticket_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("issue_ticket_id") UUID issueTicketId,
        @Parameter(name = "IssueTicketStatusUpdateRequest", description = "") @Valid @RequestBody(required = false) Optional<IssueTicketStatusUpdateRequest> issueTicketStatusUpdateRequest
    );


    /**
     * POST /projects/{project_id}/issues-tickets : register
     * register
     *
     * @param projectId  (required)
     * @param issueTicket  (optional)
     * @return succeeded (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Unprocessable Entity (status code 422)
     */
    @Operation(
        operationId = "projectsProjectIdIssuesTicketsPost",
        summary = "register",
        description = "register",
        tags = { "issues" },
        responses = {
            @ApiResponse(responseCode = "200", description = "succeeded"),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ValidationError.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unprocessable Entity", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/projects/{project_id}/issues-tickets",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> projectsProjectIdIssuesTicketsPost(
        @Parameter(name = "project_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("project_id") UUID projectId,
        @Parameter(name = "IssueTicket", description = "") @Valid @RequestBody(required = false) Optional<IssueTicket> issueTicket
    );

}
