/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.issuemanager.presentation.api;

import com.example.issuemanager.presentation.model.Error;
import java.util.UUID;
import com.example.issuemanager.presentation.model.User;
import com.example.issuemanager.presentation.model.UsersPostRequest;
import com.example.issuemanager.presentation.model.ValidationError;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-05-12T03:11:22.970089+09:00[Asia/Tokyo]", comments = "Generator version: 7.5.0")
@Validated
@Tag(name = "users", description = "manage users")
public interface UsersApi {

    /**
     * GET /users : retrieve given users
     *
     * @param userIds  (optional)
     * @return succeeded (status code 200)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "usersGet",
        summary = "retrieve given users",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "succeeded", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = User.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<User>> usersGet(
        @Parameter(name = "user_ids", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "user_ids", required = false) Optional<List<UUID>> userIds
    );


    /**
     * GET /users/me : retrieve
     * retrieve
     *
     * @return succeeded (status code 200)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "usersMeGet",
        summary = "retrieve",
        description = "retrieve",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "succeeded", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = User.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users/me",
        produces = { "application/json" }
    )
    
    ResponseEntity<User> usersMeGet(
        
    );


    /**
     * POST /users : register
     *
     * @param usersPostRequest  (optional)
     * @return succeeded (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Unprocessable Entity (status code 422)
     */
    @Operation(
        operationId = "usersPost",
        summary = "register",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "succeeded"),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ValidationError.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unprocessable Entity", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/users",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> usersPost(
        @Parameter(name = "UsersPostRequest", description = "") @Valid @RequestBody(required = false) Optional<UsersPostRequest> usersPostRequest
    );


    /**
     * GET /users/{user_id} : retrieve
     * retrieve
     *
     * @param userId  (required)
     * @return succeeded (status code 200)
     *         or Unauthorized (status code 401)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "usersUserIdGet",
        summary = "retrieve",
        description = "retrieve",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "succeeded", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = User.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users/{user_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<User> usersUserIdGet(
        @Parameter(name = "user_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("user_id") UUID userId
    );

}
